### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by kazu0617** [Psychpsyo/DefaultTooltips#2]
i18n support to use other country users.
i can provide japanese one.

**Comment by Psychpsyo** [comment]
I've added initial support for this now.
You can copy en.json from the locales folder to use it as the basis for ja.json

~~NOTE: Currently your locale needs to have all keys, otherwise it'll throw errors in the logs.
It also doesn't yet detect it when you switch your language setting while the game is running.~~

~~I'll work on both of those once I've got more of the default UI supported.~~
All of those now exist.

**Comment by Psychpsyo** [comment]
I have now improved support. (it was actually broken)
It now works and you can also switch away and back to your language while the game is running to make it reload the locale files it is using.
You also don't need every locale string in your translation anymore, missing ones will just fall back to English.
